phases:
  build:
    commands:
      - ls -la
      - sam build -t template.yaml
  post_build:
    commands:
      - sam deploy --region us-east-2 -t template.yaml --stack-name receipt-platform-dev --capabilities CAPABILITY_IAM --resolve-s3 --no-fail-on-empty-changeset
